- examples/006_submitting_forms.php
`$client' was never instantiated in this example (006).
> (typo) Instantiate the HTTP client

- lib/Client.php
Adds support for setting a default user agent to override the Artax UA.
The reason for this is so that API clients can specify the library sending requests instead of the underlying HTTP client doing the "leg work". This would provide an easy way for these clients to set the UA on every request it sends.
I didn't provide a test because there were slim pickins' in the existing test. I wouldn't mind writing a test for this but would probably need some guidance on the best way to approach that.
> Allow setting default user agent option

- lib/Uri.php
- Removes trailing and leading whitespace from the Uri file
- Ensures that the 2nd argument passed to `http_build_query` passes strict type hints
> Fix strict types in Uri

- README.md
- lib/Client.php
- lib/Parser.php
The primary use case for this PR is being able to set the `Parser::OP_MAX_BODY_BYTES` option for consuming streaming connections (e.g. the Twitter streaming API). This patch ensures that when handling these types of connections we can configure the Parser appropriately to not check body size. Otherwise after the data limit is hit an error is thrown and the connection is lost.
The rest of the options were added as they seemed relevant (there was a TODO for the body swap size) and it made sense to hit them all at once.
> Exposes relevant parser options to client

- README.md
- lib/Client.php
- lib/Notify.php
This allows inspecting the stream meta data, e.g. the crypto info. The first
item is as always the Notify ID, the second item is the stream meta data as
returned from `stream_get_meta_data()`. This notification fires always before
a request is written.
> Add Notify::HANDSHAKE_COMPLETE

- lib/SocketPool.php
Was getting: 
`TypeError: Argument 1 passed to Amp\Loop::disable() must be of the type string, null given`
not sure why idleWatcher was null, so perhaps there is some other issue that needs fixing, but I did notice that other parts of SocketPool do check the status of idleWatcher before passing it to Loop operations.
> Check if idleWatcher exists before disabling loop

- lib/FormBody.php
This is RFC + otherwise aerys cuts of the last 2 bytes of the last multipart field
> Multipart body must end with \r\n

- lib/Internal/Parser.php
Yes, I am serious. Really. Despite that, avoiding one-char-vars increases code readability
[E_NOTICE] Undefined variable: m in /www/jaumo/vendor/amphp/artax/lib/Internal/Parser.php (Line 184)
Renaming the vars fixes the issue. Don't ask me why but we REALLY have that problem in production!
> Avoid single-char vars due to a bug in PHP 7.1.9

- lib/DefaultClient.php
- lib/Internal/RequestCycle.php
Previously the client tried to consume response bodies in case the body
wasn't consumed. That might have left sockets open indefinitely. These
sockets are now closed instead.
Additionally, this commit fixes the transfer timeout, which wasn't
enforced after the headers had been received.
Furthermore, it adds a check that Artax has received the full response
body and the connection wasn't closed pre-maturely.
> Close sockets correctly for timeouts and incomplete bodies

- examples/7-unix-sockets.php
Hey, just stumbled upon the failed Travis CI Test due to unused use statements. I just removed them in this PR.
> Removed unused imports breaking tests

- lib/Request.php
Not sure how common of a use case this is, but it is an issue I ran into.
All tests pass, except for the one mentioned in #169.
> allow objects with __toString method as withHeaders array value

- lib/DefaultClient.php
- test/ClientHttpBinIntegrationTest.php
Currently the test-suite fails since the "server closes socket after accept"-test assumes that results in an error when the response is read. In reality byte-stream already fails on write.
This adds a `catch`-clause for the byte-stream exception, converts it to an artax SocketException and changes the unit-test to expect the correct exception message.
> Fix unit-test failure in client integration test

- examples/6-concurrent-requests.php
- src/Connection/DefaultConnectionPool.php
- src/Connection/Http2Connection.php
- src/Response.php
- test/Interceptor/AddRequestHeaderTest.php
- test/Interceptor/AddResponseHeaderTest.php
- test/Interceptor/InterceptorTest.php
- test/Interceptor/RemoveRequestHeaderTest.php
One connection might be enough for HTTP/2, but usually isn't for HTTP/1.
> Ignore errors of previous connections, try to connect concurrently

- docs/interceptors.md
- src/Client.php
- test/ClientHttpBinIntegrationTest.php
- test/Interceptor/InterceptorTest.php
- test/TimeoutTest.php
Extension of #198. @kelunik thoughts on the last commit?
> Immutable client

- src/Connection/Connection.php
- src/Connection/DefaultConnectionPool.php
- src/Connection/Http1Connection.php
- src/Connection/Http2Connection.php
This is an attempt to add a method to the `Connection` interface that can be used test a connection to determine if it should be used for a request, particular a non-idempotent request.
Not sure on naming or the approach for HTTP/1.x connections.
> Move liveliness check to Connection interface

- src/Connection/Http1Connection.php
- src/Connection/Http2Connection.php
- src/Connection/HttpStream.php
- src/Connection/InterceptedStream.php
- src/Interceptor/RetryRequests.php
- src/PooledHttpClient.php
- src/Request.php
- test/RequestTest.php
All properties are either immutable for deep clones now.
Fixes #216.
> Ensure clones of Request are deep clones

- src/Connection/UnlimitedConnectionPool.php
If a prior HTTPS connection returned a non-H2 connection, the pool assumes the next connection will also not be H2.
Related to #246.
> Store if an H2 connection was made

- composer.json
The missing branch-alias prevents us from installing dev-master easily.
> Add branch-alias in composer.json

- src/HttpClientBuilder.php
Alternative implementation to #238. Closes #238.
> Allow skipping the default interceptors in HttpClientBuilder

- src/Connection/Http1Connection.php
- src/Connection/Internal/Http2ConnectionProcessor.php
- src/Request.php
Will be required to complete https://github.com/symfony/symfony/pull/35115
Draft state for now until I confirm this allows passing the `testInformationalResponseStream()` test case.
Still, WDYT?
See https://evertpot.com/http/103-early-hints
> Add Request::onInformationalResponseHandler() to process e.g. 103 Early Hints

- src/Connection/Http1Connection.php
- src/Connection/Internal/Http2ConnectionProcessor.php
- src/Connection/Internal/Http2Stream.php
Not sure whether HTTP/1 or HTTP/2 is better in calling `startReceivingResponse`, technically, these are indeed two responses that are started, but one is only intermediate. Should it trigger for the intermediate, the actual response or both?
> Await events @ HTTP/2

- src/Connection/ConnectionLimitingPool.php
- src/Connection/Http1Connection.php
> Tally active requests in pool to close unsuited, idle connections

- src/Connection/Http1Connection.php
- src/Connection/Http2Connection.php
- src/Connection/Internal/Http2ConnectionProcessor.php
- src/Connection/Internal/Http2Stream.php
- src/Request.php
- test/ClientHttpBinIntegrationTest.php
- test/Connection/Http1ConnectionTest.php
- test/Connection/Http2ConnectionTest.php
This provides a separate timeout while waiting for the response or streaming the body. If no data is received for the response within the given number of milliseconds, the request fails similarly to the transfer timeout.
> Add inactivity timeout

- composer.json
I'm trying to use `"amphp/file": "dev-master as 1.0.1",` in my composer.json because of https://github.com/amphp/file/commit/7dc65ffc03d236bf0465b83ed7767f043f502873 but composer refuses to install it:
```
Problem 1
- amphp/file dev-master conflicts with amphp/http-client[v4.2.2].
- amphp/http-client v4.2.2 conflicts with amphp/file[dev-master].
- amphp/file dev-master conflicts with amphp/http-client[v4.2.2].
- Installation request for amphp/file dev-master as 1.0.1 -> satisfiable by amphp/file[dev-master].
- Installation request for amphp/http-client (locked at v4.2.2, required as ^4.0) -> satisfiable by amphp/http-client[v4.2.2].
```
Now there are two ways to fix this:
1. Add [branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) to amphp/file to let composer know …
> Make conflict with amphp/file lax

- src/Connection/DefaultConnectionFactory.php
- src/Connection/Internal/Http2ConnectionProcessor.php
- test/ClientHttpBinIntegrationTest.php
Inspired by https://github.com/symfony/symfony/issues/36419. In not sure whether we'll support upgrades without prior knowledge.
> Support direct HTTP/2 connections without TLS

- src/Connection/ConnectionPool.php
- src/Connection/HttpStream.php
- src/Connection/Internal/Http2ConnectionProcessor.php
- src/Connection/Stream.php
- src/Connection/StreamLimitingPool.php
- src/Interceptor/RetryRequests.php
- src/Request.php
- src/Response.php
- test/Connection/Http2ConnectionTest.php
GOAWAY doesn't mean we should close the connection right away, but rather that we shouldn't send any new requests on that connection.
Additionally, if we experience timeouts, ping before making a new request, to ensure that non-responsive but non-idle connections are sorted out and not reused.
> Fix HTTP/2 shutdown

- src/Connection/ConnectionLimitingPool.php
- test/Connection/ConnectionLimitingPoolTest.php
Fix for #277. I've included a test as well, although it's kind of a mess. The closures modifying each other's values by reference is kind of hacky, and the value of $numRequests is based on the hard-coded limit of 64 in `ConnectionLimitingPool->onReadyConnection`.  I had to actually implement the onClose callbacks to test when the pool closes idle connections, and I don't think I can use a PHPUnit expectation to verify when the connection is closed because we need to know that the connection was closed after the request promise was fulfilled, not just after the method was called. I'm open to any suggestions on how to improve it.
> Fix ConnectionLimitingPool closing non-idle connections

- docs/concurrent.md
$client->request now uses a Request as the parameter, not a url string
> request() needs Request as the parameter, not a string
